# ‚ö†Ô∏è THIS WORKFLOW IS USED TO ILLUSTRATE lowlighter/metrics FEATURES
# INTENDED FOR TESTING, IT IS NOT OPTIMIZED AND SHOULD NOT BE RE-USED

name: Metrics (examples)
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
jobs:
  github-metrics-examples:
    runs-on: ubuntu-latest
    if: "github.repository == 'shimanto-rehman/shimanto-rehman'"
    steps:

      # ======================================================================================
      # üñºÔ∏è TEMPLATES
      # ======================================================================================

      - name: üìó Classic template
        if: ${{ success() || failure() }}
        uses: shimanto-rehman/metrics@main
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          plugins_errors_fatal: ${{ github.repository == 'shimanto-rehman/shimanto-rehman' }}
          output_action: pull-request
          delay: 120

      # ======================================================================================
      # üí° Coding habits

      - name: üí° Coding habits
        if: ${{ success() || failure() }}
        uses: shimanto-rehman/metrics@main
        with:
          filename: metrics.plugin.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugins_errors_fatal: ${{ github.repository == 'shimanto-rehman/shimanto-rehman' }}
          config_timezone: Europe/Paris
          output_action: pull-request
          delay: 120

      - name: üí° Coding habits (facts)
        if: ${{ success() || failure() }}
        uses: shimanto-rehman/metrics@main
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugins_errors_fatal: ${{ github.repository == 'shimanto-rehman/shimanto-rehman' }}
          config_timezone: Europe/Paris
          output_action: pull-request
          delay: 120

      - name: üí° Coding habits (charts)
        if: ${{ success() || failure() }}
        uses: shimanto-rehman/metrics@main
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugins_errors_fatal: ${{ github.repository == 'shimanto-rehman/shimanto-rehman' }}
          config_timezone: Europe/Paris
          output_action: pull-request
          delay: 120

      
