# âš ï¸ THIS WORKFLOW IS USED TO ILLUSTRATE lowlighter/metrics FEATURES
# INTENDED FOR TESTING, IT IS NOT OPTIMIZED AND SHOULD NOT BE RE-USED

name: Metrics (examples)
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
jobs:
  github-metrics-examples:
    runs-on: ubuntu-latest
    if: "github.repository == 'lowlighter/lowlighter'"
    steps:

      # ======================================================================================
      # ðŸ–¼ï¸ TEMPLATES
      # ======================================================================================

      - name: ðŸ“— Classic template
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      - name: ðŸ“˜ Repository template
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          template: repository
          filename: metrics.repository.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          user: lowlighter
          repo: metrics
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          plugin_projects_repositories: lowlighter/metrics/projects/1
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      - name: ðŸ“™ Terminal template
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          template: terminal
          filename: metrics.terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, metadata
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      - name: ðŸ“’ Markdown template
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          template: markdown
          filename: metrics.markdown.md
          markdown: metrics.markdown.template.md
          config_output: markdown
          token: ${{ secrets.METRICS_TOKEN }}
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      - name: ðŸ“’ Markdown template (with plugins)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          template: markdown
          filename: metrics.markdown.full.md
          markdown: https://raw.githubusercontent.com/lowlighter/metrics/master/source/templates/markdown/example.md
          config_output: markdown
          plugin_activity: yes
          plugin_activity_limit: 7
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugin_posts_descriptions: yes
          plugin_posts_covers: yes
          plugin_posts_limit: 2
          plugin_rss: yes
          plugin_rss_source: https://news.ycombinator.com/rss
          plugin_rss_limit: 4
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_user: github
          plugin_tweets_attachments: yes
          plugin_tweets_limit: 2
          plugin_topics: yes
          plugin_topics_limit: 24
          plugin_isocalendar: yes
          plugin_languages: yes
          token: ${{ secrets.METRICS_TOKEN }}
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      - name: ðŸ“’ Markdown template (pdf output)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          template: markdown
          filename: metrics.markdown.pdf
          markdown: https://raw.githubusercontent.com/lowlighter/metrics/master/source/templates/markdown/example.pdf.md
          config_output: markdown-pdf
          plugin_rss: yes
          plugin_rss_source: https://news.ycombinator.com/rss
          plugin_rss_limit: 4
          plugin_isocalendar: yes
          config_twemoji: yes
          config_padding: 5%
          token: ${{ secrets.METRICS_TOKEN }}
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120
      # ======================================================================================
      # ðŸ’¡ Coding habits

      - name: ðŸ’¡ Coding habits
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          config_timezone: Europe/Paris
          output_action: pull-request
          delay: 120

      - name: ðŸ’¡ Coding habits (facts)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          config_timezone: Europe/Paris
          output_action: pull-request
          delay: 120

      - name: ðŸ’¡ Coding habits (charts)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          config_timezone: Europe/Paris
          output_action: pull-request
          delay: 120

      # ======================================================================================
      # ðŸ™‹ Introduction

      - name: ðŸ™‹ Introduction (user)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.introduction.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          user: github
          base: header
          plugin_introduction: yes
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      - name: ðŸ™‹ Introduction (repository)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.introduction.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: repository
          repo: metrics
          base: header
          plugin_introduction: yes
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120
# ======================================================================================
# Special job used to render markdown as png
# ======================================================================================

  github-metrics-markdown:
    runs-on: ubuntu-latest
    if: "github.repository == 'lowlighter/lowlighter'"
    container: ghcr.io/lowlighter/metrics:master
    steps:

      - name: Screenshot markdown example
        run: |
          node /metrics/.github/markdown_example.mjs
          echo "METRICS_MARKDOWN_EXAMPLE=$(base64 --wrap=0 metrics.markdown.png)" >> $GITHUB_ENV

      - name: Update markdown example
        uses: actions/github-script@v5
        env:
          METRICS_MARKDOWN_EXAMPLE: "${{ env.METRICS_MARKDOWN_EXAMPLE }}"
        with:
          debug: yes
          script: |
            try {
              const {data:{sha}} = await github.rest.repos.getContent({...context.repo, path:"metrics.markdown.png"})
              console.log(`current sha: ${sha}`)
              github.rest.repos.createOrUpdateFileContents({
                ...context.repo,
                path:"metrics.markdown.png",
                message:`Auto-generated metrics for run #${github.context ? github.context.runId : "0000000000"}`,
                content:process.env.METRICS_MARKDOWN_EXAMPLE,
                sha,
              })
            } catch (error) { console.log(error) }

# ======================================================================================
# Special job used to render lowlighter/metrics repository assets
# ======================================================================================

  github-metrics-repository:
    runs-on: ubuntu-latest
    if: "github.repository == 'lowlighter/lowlighter'"
    steps:

      - name: Contributors
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.contributors.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          user: lowlighter
          repo: metrics
          plugin_people: yes
          plugin_people_types: contributors
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          config_display: large
          output_action: pull-request
          delay: 120

      - name: Sponsors
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.sponsors.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_types: sponsors
          plugin_people_sponsors_custom: lowlighter, yutkat, ktnkk, iamsainikhil, tfSheol
          plugin_people_size: 48
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          config_display: large
          output_action: pull-request
          delay: 120

      - name: Licenses
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.licenses.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          repo: metrics
          plugin_licenses: yes
          plugin_licenses_setup: npm ci
          plugin_licenses_legal: yes
          plugin_licenses_ratio: yes
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120
